services:
  # --- BACKEND (FastAPI) ---
  backend:
    image: ghcr.io/${REPO_NAME}-backend:${APP_TAG}
    container_name: ${PROJECT_ID}-api
    environment:
      - APP_PATH=${APP_PATH}
      - ENV=${ENV}
      - UPLOAD_DIR=/app/data
    volumes :
      - ./data-${PROJECT_ID}:/app/data
    networks:
      - proxfleet-internal
    restart: always

  # --- FRONTEND (Nginx + React) ---
  frontend:
    image: ghcr.io/${REPO_NAME}-frontend:${APP_TAG}
    container_name: ${PROJECT_ID}-ui
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${PROJECT_ID}.rule=Host(`proxfleet.usmb-tri.fr`) && PathPrefix(`${APP_PATH}`)"
      - "traefik.http.routers.${PROJECT_ID}.entrypoints=websecure"
      - "traefik.http.routers.${PROJECT_ID}.tls.certresolver=mon-ovh"
      
      # Middleware pour enlever le préfixe (/app2 ou /app2-dev)
      - "traefik.http.middlewares.cut-${PROJECT_ID}.stripprefix.prefixes=${APP_PATH}"
      - "traefik.http.routers.${PROJECT_ID}.middlewares=cut-${PROJECT_ID}"
      - "traefik.http.middlewares.add-slash-${PROJECT_ID}.redirectregex.regex=^.*${APP_PATH}$$"
      - "traefik.http.middlewares.add-slash-${PROJECT_ID}.redirectregex.replacement=${APP_PATH}/"
      - "traefik.http.routers.${PROJECT_ID}.middlewares=add-slash-${PROJECT_ID},cut-${PROJECT_ID}"
      - "traefik.docker.network=reverse_proxy"
      - "traefik.http.services.${PROJECT_ID}.loadbalancer.server.port=80"
    networks:
      - reverse_proxy
      - proxfleet-internal
    restart: always

networks:
  proxfleet-internal:
    driver: bridge
  reverse_proxy:
    external: true