from proxmoxer import ProxmoxAPI
from proxmoxer.core import ResourceException
from api.exceptions.exceptions import ProxmoxAPIError

import uuid
import time

class ProxmoxAuth:
    def __init__( self,proxmox_host: str,proxmox_user, proxmox_password=None,use_token=False, token_name=None, token_value=None,verify_ssl: bool = True):
        """
        Docstring pour __init__
        
        :param self: Description
        :param host: Description
        :param proxmox_user: Description
        :param proxmox_password: Description
        """
        
        self.host = proxmox_host
        self.proxmox_user = proxmox_user
        
        if use_token:
            self.proxmox = ProxmoxAPI(proxmox_host, user=proxmox_user, token_name=token_name, token_value=token_value, verify_ssl=verify_ssl)
        else:
            self.proxmox = ProxmoxAPI(proxmox_host, user=proxmox_user, password=proxmox_password, verify_ssl=verify_ssl)


    def create_token(self,comment="",privsep:int = 1,ttl_seconds:int = 3600) -> dict:
        """
        Create an API token for the targeted user
            
        :param self: 
        comment : 
        expiration : API token expiration date
        """
            
        tokenid = f"proxfleet-{uuid.uuid4().hex[:12]}"
        expire = int(time.time()) + ttl_seconds

        try:
            result = self.proxmox.access.users(self.proxmox_user).token(tokenid).post(expire=expire,privsep=privsep,comment=comment)

            return {"tokenid": tokenid,"value": result["value"],"expire": int(result["info"]["expire"]),"privsep": int(result["info"]["privsep"])}
        
        except ResourceException as e:
            raise RuntimeError(f"Proxmox token creation failed: {e}")

    def delete_token(self, token_id: str) -> None:
        """
        Delete the API token for the targeted user.
        
        :param token_id: The user-specific token identifier.
        """
        try:
            # L'appel à l'API Proxmox
            self.proxmox.access.users(self.proxmox_user).token(token_id).delete()
        except Exception as e:
            # On lève notre exception métier spécifique au lieu d'une Exception générique
            raise ProxmoxAPIError(
                message=f"Failed to delete token '{token_id}' for user '{self.proxmox_user}': {str(e)}"
            )

    def clean_old_tokens(self, prefix: str = "proxfleet-") -> None:
        """
        Delete all old tokens generated by the application for the targeted user.
        Must be called using a password-authenticated instance.
        """
        try:
            # Directly query the specific endpoint for user tokens
            # This returns a list of dictionaries
            tokens = self.proxmox.access.users(self.proxmox_user).token.get()
            
            for token in tokens:
                # Each token is a dict containing details like 'tokenid', 'expire', etc.
                token_id = token.get("tokenid", "")
                
                # Check if the token was generated by this application
                if token_id.startswith(prefix):
                    try:
                        self.proxmox.access.users(self.proxmox_user).token(token_id).delete()
                    except Exception as e:
                        print(f"Failed to delete old token {token_id}: {str(e)}")
                        
        except Exception as e:
            print(f"Error while fetching tokens for cleanup: {str(e)}")